// Constructor
/*
it is special function which is invoked automatically when the object is created
name of constuctor must be same as class
it doesn't have any type of datatype
it is used to initialize the value
see OOPS6, OOPS7
constuctor can be used to open file and gather resources before excecuting the whole program
constuctor is called in order as object are made and destructor are called in reverse order
Destructor is instance member function that is invoked automatically when a object is going to be destroyed
it is the last fnction to be called before a object is destroyed
see OOP8
*/